# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: interface                # plugin type (gateway, interface, protocol, system, web)
    description:
        de: "Steuerung eines Apple TV's"
        en: 'Controls an Apple TV'
        fr: 'Contrôle un Apple TV'
    maintainer: Foxi352
    tester: onkelandy
    state: ready
    keywords: appletv media
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1223483-plugin-apple-tv

    version: 1.6.2                  # Plugin version
    sh_minversion: 1.6              # minimum shNG version to use this plugin
    multi_instance: True            # plugin supports multi instance
    restartable: unknown
    classname: AppleTV              # class containing the plugin

parameters:
    ip:
        type: ip
        default: 0.0.0.0
        description:
            de: 'IP Adresse des Gerätes. Bei 0.0.0.0 wir das erste erkannte Gerät genutzt.'
            en: 'Device IP address. 0.0.0.0 uses the first detected device.'
            fr: "Adresse IP de l'appareil. 0.0.0.0 pour utiliser le premier appareil détecté."
    scan_timeout:
        type: num
        default: 5
        description:
            de: 'Timeout in Sekunden beim scannen des Netzwerkes nach AppleTV Geräten'
            en: 'Timeout in seconds to scan the local network for AppleTV devices'
            fr: "Délai d'attente en secondes du scan réseau pour trouver les appareils AppleTV"

item_attributes:
    appletv:
        type: str
        description:
            de: 'ATV Funktion'
            en: 'ATV function'
        valid_list_description:
          de:
            - 'AppleTV Name'
            - 'AppleTV IP Adresse'
            - 'AppleTV MAC'
            - 'AppleTV Modell'
            - 'AppleTV OS Version'
            - 'Einschaltstatus'
            - 'Applikationsidentifikation'
            - 'Applikationsname'
            - 'Abspielstatus als Zahl'
            - 'Abspielstatus als Text'
            - 'Fingerprint des aktuellen Mediums'
            - 'Aktuelles Genre'
            - 'Aktueller Künstler'
            - 'Aktuelles Album'
            - 'Aktueller Titel'
            - 'Aktueller Medientyp als Zahl'
            - 'Aktueller Medientyp als Text'
            - 'Aktuelle Zeitposition'
            - 'Aktuelle Gesamtspielzeit'
            - 'Aktuelle Abspielposition in Prozent'
            - 'Aktueller Wiederholmodus als Zahl'
            - 'Aktueller Wiederholmodus als Text'
            - 'Aktueller Shuffle Modus als Zahl'
            - 'Aktueller Shuffle Modus als Text'
            - 'Breite des aktuellen Artworks in Pixel'
            - 'Höhe des aktuellen Artworks in Pixel'
            - 'Mimetype des aktuellen Artorks'
            - 'Tatsächliches aktuelles Artwork'
            - 'Topmenü Taste'
            - 'Home Taste'
            - 'Hold home Taste'
            - 'Menü Taste'
            - 'Auswählen Taste'
            - 'Nächster Titel'
            - 'Vorheriger Titel'
            - 'Abspielen'
            - 'Pause'
            - 'Stop'
            - 'Umschalten zwischen Play und Pause'
            - 'Hinunter Taste'
            - 'Hinauf Taste'
            - 'Links Taste'
            - 'Rechts Taste'
            - 'Abspielposition setzen'
            - 'Wiederholmodus setzen'
            - 'Shuffle Modus setzen'
            - 'Rückwärts springen'
            - 'Vorwärts springen'
            - 'Lautstärke verringern'
            - 'Lautstärke erhöhen'
            - 'Suspend Modus'
            - 'Aufwecken'
          en:
            - 'AppleTV name'
            - 'AppleTV IP address'
            - 'AppleTV MAC'
            - 'AppleTV Model'
            - 'AppleTV OS version'
            - 'Power State'
            - 'App identifier of playing application'
            - 'App name of playing application'
            - 'Playing State as number'
            - 'Playing State as text'
            - 'Fingerprint of currently played media'
            - 'Currently playing genre'
            - 'Currently playing artist'
            - 'Currently playing album'
            - 'Currently playing title'
            - 'Currently playing media type as number'
            - 'Currently playing media type as text'
            - 'Current time position'
            - 'Current total time'
            - 'Current playing position in percent'
            - 'Current repeat setting as number'
            - 'Current repeat setting as text'
            - 'Current shuffle setting as number'
            - 'Current shuffle setting as text'
            - 'Width in pixels of current art work'
            - 'Height in pixels of current art work'
            - 'Mimetype of current art work'
            - 'Actual playing artwork'
            - 'Top menu key'
            - 'Home key'
            - 'Hold home key'
            - 'Menu key'
            - 'Select key'
            - 'Next'
            - 'Previous'
            - 'Play'
            - 'Pause'
            - 'Stop'
            - 'Toggle play/pause'
            - 'Down key'
            - 'Up key'
            - 'Left key'
            - 'Right key'
            - 'Set play position'
            - 'Set repeat mode'
            - 'Set shuffle mode'
            - 'Skip backward'
            - 'Skip forward'
            - 'Volume down'
            - 'Volume up'
            - 'Suspend mode'
            - 'Wake up'
        valid_list:
          - 'name'
          - 'ip'
          - 'mac'
          - 'model'
          - 'os'
          - 'power'
          - 'playing_app_identifier'
          - 'playing_app_name'
          - 'playing_state'
          - 'playing_state_text'
          - 'playing_fingerprint'
          - 'playing_genre'
          - 'playing_artist'
          - 'playing_album'
          - 'playing_title'
          - 'playing_type'
          - 'playing_type_text'
          - 'playing_position'
          - 'playing_total_time'
          - 'playing_position_percent'
          - 'playing_repeat'
          - 'playing_repeat_text'
          - 'playing_shuffle'
          - 'playing_shuffle_text'
          - 'artwork_width'
          - 'artwork_height'
          - 'artwork_mimetype'
          - 'artwork_base64'
          - 'rc_top_menu'
          - 'rc_home'
          - 'rc_home_hold'
          - 'rc_menu'
          - 'rc_select'
          - 'rc_next'
          - 'rc_previous'
          - 'rc_play'
          - 'rc_pause'
          - 'rc_stop'
          - 'rc_play_pause'
          - 'rc_down'
          - 'rc_up'
          - 'rc_left'
          - 'rc_right'
          - 'rc_set_position'
          - 'rc_set_repeat'
          - 'rc_set_shuffle'
          - 'rc_skip_backward'
          - 'rc_skip_forward'
          - 'rc_volume_down'
          - 'rc_volume_up'
          - 'rc_suspend'
          - 'rc_wakeup'


item_structs:
    device:
        remark:
            remark: Name of device
            type: str
            visu_acl: ro
            cache: True
            appletv@instance: name
        ip:
            remark: IP address of device
            type: str
            visu_acl: ro
            cache: True
            appletv@instance: ip
        mac:
            remark: MAC address of device
            type: str
            visu_acl: ro
            cache: True
            appletv@instance: mac
        model:
            remark: MAC address of device
            type: str
            visu_acl: ro
            cache: True
            appletv@instance: model
        os:
            remark: MAC address of device
            type: str
            visu_acl: ro
            cache: True
            appletv@instance: os
        power:
            remark: Power state of the device
            type: bool
            visu_acl: rw
            appletv@instance: power
    playing:
        app:
            identifier:
                type: str
                visu_acl: ro
                cache: True
                appletv@instance: playing_app_identifier
            remark:
                type: str
                visu_acl: ro
                cache: True
                appletv@instance: playing_app_name
        state:
            type: num
            visu_acl: ro
            cache: True
            appletv@instance: playing_state
        state_text:
            type: str
            visu_acl: ro
            cache: True
            appletv@instance: playing_state_text
        fingerprint:
            type: str
            visu_acl: ro
            cache: True
            appletv@instance: playing_fingerprint
        genre:
            type: str
            visu_acl: ro
            cache: True
            appletv@instance: playing_genre
        artist:
            type: str
            visu_acl: ro
            cache: True
            appletv@instance: playing_artist
        album:
            type: str
            visu_acl: ro
            cache: True
            appletv@instance: playing_album
        title:
            type: str
            visu_acl: ro
            cache: True
            appletv@instance: playing_title
        media_type:
            type: num
            visu_acl: ro
            cache: True
            appletv@instance: playing_type
        media_type_text:
            type: str
            visu_acl: ro
            cache: True
            appletv@instance: playing_type_text
        position:
            type: num
            visu_acl: ro
            cache: True
            appletv@instance: playing_position
        totaltime:
            type: num
            visu_acl: ro
            cache: True
            appletv@instance: playing_total_time
        position_percent:
            type: num
            visu_acl: rw
            cache: True
            appletv@instance: playing_position_percent
        repeat:
            type: num
            visu_acl: rw
            cache: True
            enforce_updates: True
            appletv@instance: playing_repeat
        repeat_text:
            type: str
            visu_acl: ro
            cache: True
            appletv@instance: playing_repeat_text
        shuffle:
            type: num
            visu_acl: rw
            cache: True
            enforce_updates: True
            appletv@instance: playing_shuffle
        shuffle_text:
            type: str
            visu_acl: ro
            cache: True
            appletv@instance: playing_shuffle_text
        artwork:
            width:
                remark: Width of the currently playing artwork
                type: num
                visu_acl: ro
                appletv@instance: artwork_width
            height:
                remark: Height of the currently playing artwork
                type: num
                visu_acl: ro
                appletv@instance: artwork_height
            mimetype:
                remark: Mimetype of the currently playing artwork
                type: str
                visu_acl: ro
                appletv@instance: artwork_mimetype
            base64:
                remark: The actual playing artwork in base64
                type: foo
                visu_acl: ro
                appletv@instance: artwork_base64
    commands:
        top_menu:
            remark: RC top menu key
            type: bool
            visu_acl: rw
            appletv@instance: rc_top_menu
        home:
            remark: RC kome key
            type: bool
            visu_acl: rw
            appletv@instance: rc_home
        home_hold:
            remark: RC hold home key
            type: bool
            visu_acl: rw
            appletv@instance: rc_home_hold
        menu:
            remark: RC menu key
            type: bool
            visu_acl: rw
            appletv@instance: rc_menu
        select:
            remark: RC select key
            type: bool
            visu_acl: rw
            appletv@instance: rc_select
        next:
            remark: RC next key
            type: bool
            visu_acl: rw
            appletv@instance: rc_next
        previous:
            remark: RC previous key
            type: bool
            visu_acl: rw
            appletv@instance: rc_previous
        pause:
            remark: RC pause key
            type: bool
            visu_acl: rw
            appletv@instance: rc_pause
        play:
            remark: RC play key
            type: bool
            visu_acl: rw
            appletv@instance: rc_play
        play_pause:
            remark: RC toggle between play and pause
            type: bool
            visu_acl: rw
            appletv@instance: rc_play_pause
        stop:
            remark: RC stop key
            type: bool
            visu_acl: rw
            appletv@instance: rc_stop
        down:
            remark: RC down key
            type: bool
            visu_acl: rw
            appletv@instance: rc_down
        up:
            remark: RC up key
            type: bool
            visu_acl: rw
            appletv@instance: rc_up
        right:
            remark: RC right key
            type: bool
            visu_acl: rw
            appletv@instance: rc_right
        left:
            remark: RC left key
            type: bool
            visu_acl: rw
            appletv@instance: rc_left
        set_position:
            remark: RC set position
            type: num
            visu_acl: rw
            appletv@instance: rc_set_position
        set_repeat:
            remark: RC set repeat mode
            type: num
            visu_acl: rw
            appletv@instance: rc_set_repeat
        set_shuffle:
            remark: RC set shuffle mode
            type: num
            visu_acl: rw
            appletv@instance: rc_set_shuffle
        skip_backward:
            remark: RC skip backward key
            type: bool
            visu_acl: rw
            appletv@instance: rc_skip_backward
        skip_forward:
            remark: RC skip forward key
            type: bool
            visu_acl: rw
            appletv@instance: rc_skip_forward
        volume_down:
            remark: RC volume down key
            type: bool
            visu_acl: rw
            appletv@instance: rc_volume_down
        volume_up:
            remark: RC volume up key
            type: bool
            visu_acl: rw
            appletv@instance: rc_volume_up
        suspend:
            remark: RC suspend key
            type: bool
            visu_acl: rw
            appletv@instance: rc_suspend
        wakeup:
            remark: RC wakeup key
            type: bool
            visu_acl: rw
            appletv@instance: rc_wakeup

logic_parameters: NONE
# Definition of logic parameters defined by this plugin

plugin_functions:
    is_on:
        type: bool
        description:
            de: "Ist das Gerät eingeschaltet"
            en: "Is device turned on"
            fr: "Est-ce que l'appareil est allumé"
    is_playing:
        type: bool
        description:
            de: "Ist das Gerät am abspielen"
            en: "Is device playing"
            fr: "Est-ce que l'appareil est en train de jouer"
    play:
        type: bool
        description:
            de: "Abspielen"
            en: "Play"
            fr: "Jouer"
    pause:
        type: bool
        description:
            de: "Pause"
            en: "Pause"
            fr: "Pause"
