# Metadata for the classic-plugin
plugin:
    # Global plugin attributes
    type: interface                 # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Integration von iRobot Roomba Staubsaugern'
        en: 'integration of iRobot Roomba vacuum cleaners'
    maintainer: 'Pacifica15'
    tester: '?'
    state: develop
    keywords: irobot roomba             # keywords, where applicable
    documentation: https://github.com/Pacifica15/smarthomeng-plugins/README.md        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

# Following entries are for Smart-Plugins:
    version: 1.0.0                 # Plugin version
    sh_minversion: 1.6             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False
    restartable: unknown
    classname: ROOMBAPY              # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml

  address:
    type: str
    default: '0.0.0.0'
    description:
      de: "Die IP Adresse des roomba Staubsaugers"
      en: "The IP address of the roomba vacuum cleaner"

  blid:
    type: str
    default: '---'
    description:
      de: "Die blid des roomba Staubsaugers -> kann mit der getpassword.py ausgelesen werden"
      en: "The blid of the roomba vacuum cleaner -> use getpassword.py to get it"

  roombaPassword:
    type: str
    default: ':1:xxx'
    description:
      de: "Das Passwort des roomba Staubsaugers -> kann mit der getpassword.py ausgelesen werden"
      en: "The password of the roomba vacuum cleaner -> use getpassword.py to get it"

  cycle:
    type: int
    default: 30
    description:
      de: "update des items alle x Sekunden, default wert 900"
      en: "update the state item every x secounds, default is 900"

item_attributes:
    # Definition of item attributes defined by this plugin

    roombapysh:
        type: str
        mandatory: True
        description:
            de: 'Befehle und Statusobjekte des Roomba Staubsaugers'
            en: 'commands and status objects of roomba vacuum cleaner'
        valid_list:
        - 'connect'                         # bool - connect command to plugin, should automatically be reset (e.g. autotimer: 7200 = False)
        - 'start'                           # bool - start command for roomba
        - 'pause'                           # bool - pause command for roomba
        - 'resume'                          # bool - resume command for roomba
        - 'stop'                            # bool - stop command for roomba
        - 'dock'                            # bool - dock command for roomba
        - 'evac'                            # bool - evac command for roomba
        - 'reset'                           # bool - reset command for roomba
        - 'locate'                          # bool - locate command for roomba
        - 'connected'                       # bool - connection status of plugin
        - 'status'                          # num - overall status: 0=not connected, 1=unknown, 2=charging, 3=running, 4=pause/stop, 5=going to dock, 6=error
        - 'error_code'                      # num - Missionsfehler-Nummer aus roombapy
        - 'error_message'                   # str - Missionsfehler-Text aus roombapy
        - 'client_error'                    # str - Verbindungsfehler zum Roomba
        - 'name'                            # str - Name des Staubsaugers
        - 'bat_cCount'                      # num - Ladezyklen der Batterie
        - 'status_batterie'                 # num - Ladezustand Batterie in %
        - 'run_nCliffs'                     # num - Anzahl "cliffs" Ereignisse
        - 'run_nPanics'                     # num - Anzahl "panics" Ereignisse
        - 'run_time'                        # str - Gesamte Laufzeit im Format hh:mm
        - 'run_nScrubs'                     # num - Anzahl Schmutzereignisse
        - 'mission_total'                   # num - Gesamtzahl der Reinigungsaktionen
        - 'mission_OK'                      # num - Anzahl erfolgreich abgeschlossene Missionen
        - 'mission_err'                     # num - Anzahl Missionen mit Fehler
        - 'MissionStatus_cycle'             # str
        - 'MissionStatus_phase'             # str
        - 'MissionStatus_error'             # num
        - 'MissionStatus_startTime'         # num (in milliseconds)
        - 'MissionStatus_expireTime'        # num (in milliseconds)
        - 'MissionStatus_initiator'         # str
        - 'MissionStatus_runTime'           # str - Aktuelle Laufzeit der Mission imm Format hh:mm:ss
        - 'dock_known'                      # bool
        - 'bin_present'                     # bool - Staubcontainer eingesetzt
        - 'bin_full'                        # bool - Staubcontainer voll
        - 'mission_state'                   # str - Missionsstatus aus roombapy
        - 'lastCommand_command'             # str - Letzter Befehl
        - 'lastCommand_time'                # num - Uhrzeit letzter Befehl (in milliseconds)
        - 'lastCommand_initiator'           # str - Auslöser letzter Befehl

item_structs: NONE
  # Definition of item-structure templates for this plugin

plugin_functions: NONE
  # Definition of plugin functions defined by this plugin

logic_parameters: NONE
  # Definition of logic parameters defined by this plugin

